apiVersion: v1
kind: Service
metadata:
  namespace: naap-internal-dev
  name: etcd-client
spec:
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
