apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-nebula-pvc
  namespace: naap-development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi